name: pystan
channels:
  - defaults
dependencies:
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - libcxx=14.0.6
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1q
  - pip=22.2.2
  - python=3.7.13
  - readline=8.2
  - setuptools=63.4.1
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - appnope==0.1.3
    - arviz==0.12.1
    - astroid==2.12.12
    - backcall==0.2.0
    - cftime==1.6.2
    - click==8.1.3
    - cycler==0.11.0
    - cython==0.29.32
    - debugpy==1.6.3
    - decorator==5.1.1
    - dill==0.3.6
    - entrypoints==0.4
    - fonttools==4.38.0
    - importlib-metadata==4.11.3
    - ipykernel==6.16.2
    - ipython==7.34.0
    - isort==5.10.1
    - jedi==0.18.1
    - joblib==1.2.0
    - jupyter-client==7.4.5
    - jupyter-core==4.11.2
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.7.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - nest-asyncio==1.5.6
    - netcdf4==1.6.0
    - nltk==3.7
    - numpy==1.21.5
    - packaging==21.3
    - pandas==1.3.5
    - parso==0.8.3
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - platformdirs==2.5.2
    - prompt-toolkit==3.0.32
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pygments==2.13.0
    - pylint==2.15.5
    - pyparsing==3.0.9
    - pystan==2.19.1.1
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pyzmq==24.0.1
    - regex==2022.9.13
    - scipy==1.7.3
    - six==1.16.0
    - statsmodels==0.13.5
    - tomli==2.0.1
    - tomlkit==0.11.5
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typed-ast==1.5.4
    - typing-extensions==3.10.0.2
    - wcwidth==0.2.5
    - wrapt==1.14.1
    - xarray==0.20.2
    - xarray-einstats==0.2.2
    - zipp==3.10.0
